# Generated by Django 2.0.1 on 2018-02-16 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.TextField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('publisher', models.TextField()),
                ('binding', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
