# Generated by Django 2.0.3 on 2018-04-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180403_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='Location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
