# Generated by Django 2.0.3 on 2018-04-13 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_auto_20180405_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_No', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='MR', max_length=3)),
                ('first_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('order_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_status', models.CharField(choices=[('PEND', 'Pending'), ('DISP', 'Dispatched'), ('DELI', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PEND', max_length=4)),
                ('order_amount', models.FloatField(blank=True, null=True)),
                ('mode_of_Payment', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('book_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Books')),
                ('order_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order_Details')),
            ],
        ),
    ]
