# Generated by Django 2.0.3 on 2018-04-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item_detail',
            old_name='Amount',
            new_name='item_Amount',
        ),
    ]
